trigger:
  branches:
    include:
    - macos

variables:
  GNS_REPOSITORY_URL: https://github.com/ValveSoftware/GameNetworkingSockets.git

jobs:
- job: build_macos
  pool:
    vmImage: 'macOS-13'

  variables:
    CMAKE_GENERATOR: Xcode

  steps:
  - task: CmdLine@2
    displayName: "Create directory structure"
    inputs:
      script: |
        mkdir Source
        mkdir Build
      workingDirectory: $(Agent.BuildDirectory)
      failOnStderr: true

  - task: CmdLine@2
    displayName: "Shallow clone GNS"
    inputs:
      script: |
        git init
        git remote add origin $(GNS_REPOSITORY_URL)
        git fetch --depth 1 origin e0d33386903202d9af61e76d69c54e46ece2f457
        git config --local advice.detachedHead false
        git checkout FETCH_HEAD
        git submodule update --init --depth 1
      workingDirectory: $(Agent.BuildDirectory)/Source
      failOnStderr: false

  - task: CmdLine@2
    displayName: "Apply patches"
    inputs:
      script: |
        git apply $(Build.SourcesDirectory)/Patches/Patch001.patch
        git apply $(Build.SourcesDirectory)/Patches/Patch002.patch
      workingDirectory: $(Agent.BuildDirectory)/Source
      failOnStderr: true

  - task: CmdLine@2
    displayName: "Brew install dependencies"
    inputs:
      script: |
        brew update
        brew reinstall openssl@1.1
        brew link --force openssl@1.1
        brew list protobuf@21 || brew install protobuf@21
        brew link --force protobuf@21
      workingDirectory: $(Agent.BuildDirectory)
      failOnStderr: false

  - task: CmdLine@2
    displayName: "CMake generate solution"
    inputs:
      script: |
        cmake -G "$(CMAKE_GENERATOR)" -T buildsystem=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CONFIGURATION_TYPES=Release -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -B Build -S Source
      workingDirectory: $(Agent.BuildDirectory)
      failOnStderr: true

  - task: Xcode@5
    inputs:
      actions: build
      configuration: Release
      xcWorkspacePath: 